In [1]:
import re
import pandas as pd

https://www.kaggle.com/datasets/bhanupratapbiswas/inventory-analysis-case-study

In [2]:
study_path = r'F:\DataSpell\Pandas_training\kaggle\Inventory Analysis Case Study\PurchasesFINAL12312016.csv'

In [155]:
# study = pd.read_csv(study_path)
# study.to_pickle(r'F:\DataSpell\Pandas_training\kaggle\Inventory Analysis Case Study\PurchasesFINAL12312016.pkl')

In [156]:
# %%time
# study = pd.read_pickle(r'F:\DataSpell\Pandas_training\kaggle\Inventory Analysis Case Study\PurchasesFINAL12312016.pkl')
# study

In [157]:
# study.to_parquet(r'F:\DataSpell\Pandas_training\kaggle\Inventory Analysis Case Study\PurchasesFINAL12312016.parquet')

In [3]:
%%time
study = pd.read_parquet(r'F:\DataSpell\Pandas_training\kaggle\Inventory Analysis Case Study\PurchasesFINAL12312016.parquet')
study

CPU times: total: 4.61 s
Wall time: 2.31 s

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2015-12-21,2016-01-02,2016-01-04,2016-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-02,2016-01-07,2016-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2015-12-24,2016-01-02,2016-01-09,2016-02-16,21.32,5,106.60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372469,49_GARIGILL_22298,49,22298,Zorvino Vyds Sangiovese,750mL,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-28,2017-01-09,2017-02-06,8.06,12,96.72,2
2372470,1_HARDERSFIELD_19556,1,19556,Zorvino Bacca Z Blackberry,750mL,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-27,2017-01-09,2017-02-06,9.39,12,112.68,2
2372471,66_EANVERNESS_22297,66,22297,Zorvino Vyds Pearz,750mL,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-26,2017-01-09,2017-02-06,6.75,12,81.00,2
2372472,69_MOUNTMEND_19557,69,19557,Zorvino Fragole Z Strawberry,750mL,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-26,2017-01-09,2017-02-06,9.39,12,112.68,2
2372473,55_DRY GULCH_22298,55,22298,Zorvino Vyds Sangiovese,750mL,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-28,2017-01-09,2017-02-06,8.06,12,96.72,2

In [ ]:
# Column Size need a fix cleaning data

In [17]:
study['Size'].str.split(' ', expand=True)[0].unique()

array(['750ml', '1.75l', '200ml', '1.5l', '50ml', 'liter', '375ml',
       '100ml', '3l', '187ml', '250ml', '500ml', '5l', '4l', '180ml',
       '5.0', '18l', '300ml', '720ml', '330ml', '3/100ml', '22.0', '5/2',
       '6l', '20l', '400ml', '0', '25.0', '19.5l', '9l', '128.0'],
      dtype=object)

In [12]:
study['Size']

array(['750ml', '1.75l', '200ml', '1.5l', '50ml', 'liter', '375ml',
       '100ml', '750ml 2 pk', '3l', '187ml 4 pk', '250ml 4 pk', '500ml',
       '187ml', '100ml 4 pk', '5l', '4l', '375ml 2 pk', '187ml 3 pk',
       '250ml', '180ml', '50ml 5 pk', '200ml 4 pk', '5.0 oz', '18l',
       '300ml', '720ml', '50ml 3 pk', '50ml 4 pk', '330ml', '750ml 3 pk',
       '3/100ml', '750ml + 2/', '750ml 4 pk', '200ml 3 pk', '375ml 3 pk',
       '50ml 12 pk', '22.0 oz', '750ml + 3/', '200ml 5 pk', '750ml + 1/',
       '5/2 oz', '6l', '20l', '400ml', '0', '25.0', '187ml 2 pk', '19.5l',
       '750ml 6 pk', '9l', '128.0 gal'], dtype=object)

## Data Cleaning

In [4]:
study.nunique()
# study.dtypes

InventoryId       245907
Store                 80
Brand              10664
Description         9652
Size                  51
VendorNumber         126
VendorName           129
PONumber            5543
PODate               319
ReceivingDate        364
InvoiceDate          373
PayDate              382
PurchasePrice       2151
Quantity             686
Dollars            33567
Classification         2
dtype: int64

In [5]:
study['Size'] = study['Size'].fillna('0').str.lower()

In [6]:
def split_number_unit(spliter):
    number = ''.join(re.findall(r'\d+\.?\d*', spliter))
    unit = ''.join(re.findall(r'[a-zA-Z]+', spliter))
    return pd.Series([number, unit])

In [162]:
study[['Size_number', 'Size Unit']] = study['Size'].apply(split_number_unit)

In [163]:
study['Size_number'] = study['Size_number'].str.replace('', '0').astype(float)

for number_col in ['Store', 'Quantity']:
    study[number_col] = study[number_col].astype(int)

for col in ['Store', 'Brand', 'VendorNumber', 'PONumber']:
    study[col] = pd.to_numeric(study[col], downcast='unsigned')

for col_category in ['Store', 'VendorName', 'Size Unit']:
  study[col_category] = study[col_category].astype('category')

In [164]:
study.drop('Size', axis=1, inplace=True)

new_columns =  ['InventoryId', 'Store', 'Brand', 'Description', 'Size_number', 'Size Unit', 'VendorNumber','VendorName', 'PONumber', 
                'PODate', 'ReceivingDate', 'InvoiceDate', 'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 
                'Classification']

study = study[new_columns]

In [165]:
study.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 17 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           category
 2   Brand           uint32
 3   Description     object
 4   Size_number     float64
 5   Size Unit       category
 6   VendorNumber    uint32
 7   VendorName      category
 8   PONumber        uint16
 9   PODate          object
 10  ReceivingDate   object
 11  InvoiceDate     object
 12  PayDate         object
 13  PurchasePrice   float64
 14  Quantity        int32
 15  Dollars         float64
 16  Classification  int64
dtypes: category(3), float64(3), int32(1), int64(1), object(6), uint16(1), uint32(2)
memory usage: 221.7+ MB

In [166]:
study

,InventoryId,Store,Brand,Description,Size_number,Size Unit,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,705000.0000,ml,105,ALTAMAR BRANDS LLC,8124,2015-12-21,2016-01-02,2016-01-04,2016-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,10.0705,l,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,10.0705,l,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-02,2016-01-07,2016-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,10.0705,l,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,705000.0000,ml,388,ATLANTIC IMPORTING COMPANY,8169,2015-12-24,2016-01-02,2016-01-09,2016-02-16,21.32,5,106.60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372469,49_GARIGILL_22298,49,22298,Zorvino Vyds Sangiovese,705000.0000,ml,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-28,2017-01-09,2017-02-06,8.06,12,96.72,2
2372470,1_HARDERSFIELD_19556,1,19556,Zorvino Bacca Z Blackberry,705000.0000,ml,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-27,2017-01-09,2017-02-06,9.39,12,112.68,2
2372471,66_EANVERNESS_22297,66,22297,Zorvino Vyds Pearz,705000.0000,ml,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-26,2017-01-09,2017-02-06,6.75,12,81.00,2
2372472,69_MOUNTMEND_19557,69,19557,Zorvino Fragole Z Strawberry,705000.0000,ml,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-26,2017-01-09,2017-02-06,9.39,12,112.68,2
2372473,55_DRY GULCH_22298,55,22298,Zorvino Vyds Sangiovese,705000.0000,ml,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-28,2017-01-09,2017-02-06,8.06,12,96.72,2

In [167]:
rename_column_dict = {
                      'Size_number': 'SizeNumber', 
                      'PONumber' : 'PurchaseOrderNumber',
                      'PODate' : 'PurchaseOrderDate',
                      'Size Unit': 'SizeUnit'
                      }

study = study.rename(columns=rename_column_dict)

In [168]:
study['SizeUnit'] = study['SizeUnit'].cat.rename_categories({'mlpk': 'ml'})

C:\Users\Zygim\AppData\Local\Temp\ipykernel_38764\2202346696.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  study['SizeUnit'] = study['SizeUnit'].replace('mlpk', 'ml')

In [169]:
# Define a dictionary with conversion rates to liters
conversion_dict = {'ml': 0.001, 'l': 1, 'liter': 1, 'oz': 0.0295735, 'gal': 3.78541, '': 0}

# Replace each unit in 'SizeUnit' with its equivalent in liters
study['SizeUnit'] = study['SizeUnit'].map(conversion_dict)

# Multiply 'SizeNumber' by 'SizeUnit' to get all sizes in liters
study['SizeNumber'] = study['SizeNumber'] * study['SizeUnit']

In [170]:
study.drop('SizeUnit', axis=1, inplace=True)

In [171]:
study

,InventoryId,Store,Brand,Description,SizeNumber,VendorNumber,VendorName,PurchaseOrderNumber,PurchaseOrderDate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,705.0000,105,ALTAMAR BRANDS LLC,8124,2015-12-21,2016-01-02,2016-01-04,2016-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,10.0705,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,10.0705,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-02,2016-01-07,2016-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,10.0705,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,705.0000,388,ATLANTIC IMPORTING COMPANY,8169,2015-12-24,2016-01-02,2016-01-09,2016-02-16,21.32,5,106.60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372469,49_GARIGILL_22298,49,22298,Zorvino Vyds Sangiovese,705.0000,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-28,2017-01-09,2017-02-06,8.06,12,96.72,2
2372470,1_HARDERSFIELD_19556,1,19556,Zorvino Bacca Z Blackberry,705.0000,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-27,2017-01-09,2017-02-06,9.39,12,112.68,2
2372471,66_EANVERNESS_22297,66,22297,Zorvino Vyds Pearz,705.0000,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-26,2017-01-09,2017-02-06,6.75,12,81.00,2
2372472,69_MOUNTMEND_19557,69,19557,Zorvino Fragole Z Strawberry,705.0000,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-26,2017-01-09,2017-02-06,9.39,12,112.68,2
2372473,55_DRY GULCH_22298,55,22298,Zorvino Vyds Sangiovese,705.0000,90058,ZORVINO VINEYARDS,13593,2016-12-19,2016-12-28,2017-01-09,2017-02-06,8.06,12,96.72,2