https://www.youtube.com/watch?v=bDhvCp3_lYw&list=PLxhYs0VkONL9h5zHZXNntPqLC1JVg9pxX&index=56

In [77]:
import pandas as pd
from string import punctuation

In [78]:
df_path = r'F:\DataSpell\Pandas_training\Youtube_videos_training\Data Cleaning\data\Customer Call List.xlsx'

In [79]:
df = pd.read_excel(df_path)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [80]:
df = df.drop_duplicates()

In [81]:
# df.drop('Not_Useful_Column', axis=1, inplace=True)

In [82]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [83]:
# df['Last_Name'] = df['Last_Name'].str.strip('123._/')
df['Last_Name'] = df['Last_Name'].str.strip(punctuation)

C:\Users\Zygim\AppData\Local\Temp\ipykernel_41660\457742054.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Last_Name'] = df['Last_Name'].str.strip(punctuation)

In [84]:
df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '0', regex=True)

df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))

df['Phone_Number'] = df['Phone_Number'].apply(lambda 
                      x: x[0:3] + '-' + 
                          x[3:6] + '-' + 
                          x[3:6] + '-' +
                          x[6:10])

df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')

df['Phone_Number']  = df['Phone_Number'].str.replace('Na--', '')

C:\Users\Zygim\AppData\Local\Temp\ipykernel_41660\1285561083.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '0', regex=True)
C:\Users\Zygim\AppData\Local\Temp\ipykernel_41660\1285561083.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))
C:\Users\Zygim\AppData\Local\Temp\ipykernel_41660\1285561083.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].apply(lambda
C:\Users\Zygim\AppData\Local\Temp\ipykernel_41660\1285561083.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')
C:\Users\Zygim\AppData\Local\Temp\ipykernel_41660\1285561083.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number']  = df['Phone_Number'].str.replace('Na--', '')

In [85]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-054-054-5054,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-064-064-3097,93 West Main Street,No,Yes,False
2,1003,Walter,White,-,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-054-054-3023,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-067-067-8034,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-076-076-2024,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,-,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-067-067-8034,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N0a---,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-054-054-5054,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,-,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,-,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-054-054-3023,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-067-067-8034,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-076-076-2024,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-054-054-5054,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-064-064-3097,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,-,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N0a---,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-067-067-8034,"910 Tatooine Road, Tatooine",Yes,N,True

In [97]:
df[['Street Address', 'State', 'Zip_Code']] = df['Address'].str.split(',', n=2, expand=True)
df

C:\Users\Zygim\AppData\Local\Temp\ipykernel_41660\1583281543.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Street Address', 'State', 'Zip_Code']] = df['Address'].str.split(',', n=2, expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-054-054-5054,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-064-064-3097,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,-,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-054-054-3023,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-067-067-8034,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-076-076-2024,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,-,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-067-067-8034,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N0a---,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-054-054-5054,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,-,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,-,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-054-054-3023,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-067-067-8034,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-076-076-2024,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-054-054-5054,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-064-064-3097,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,-,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N0a---,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-067-067-8034,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [111]:
df['Paying Customer'] = (df['Paying Customer'].str.replace('Yes', 'Y').str.replace('No', 'N'))
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-054-054-5054,"123 Shire Lane, Shire",Y,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-064-064-3097,93 West Main Street,N,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,-,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-054-054-3023,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-067-067-8034,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-076-076-2024,768 City Parkway,Y,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,-,1209 South Street,N,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-067-067-8034,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N0a---,123 Middle Earth,Y,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-054-054-5054,"25th Main Street, New York",Y,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,-,"612 Shire Lane, Shire",Y,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,-,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-054-054-3023,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-067-067-8034,343 City Parkway,Y,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-076-076-2024,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-054-054-5054,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-064-064-3097,"121 Paper Avenue, Pennsylvania",Y,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,-,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N0a---,,,Yes,True,,None,None
19,1020,Anakin,Skywalker,876-067-067-8034,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,Tatooine,None

In [113]:
# df.fillna('')
df = df.replace('N/a', '')
df = df.replace('NaN', '')

In [115]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-054-054-5054,"123 Shire Lane, Shire",Y,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-064-064-3097,93 West Main Street,N,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,-,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-054-054-3023,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-067-067-8034,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-076-076-2024,768 City Parkway,Y,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,-,1209 South Street,N,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-067-067-8034,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N0a---,123 Middle Earth,Y,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-054-054-5054,"25th Main Street, New York",Y,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,-,"612 Shire Lane, Shire",Y,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,-,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-054-054-3023,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-067-067-8034,343 City Parkway,Y,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-076-076-2024,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-054-054-5054,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-064-064-3097,"121 Paper Avenue, Pennsylvania",Y,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,-,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N0a---,,,Yes,True,,None,None
19,1020,Anakin,Skywalker,876-067-067-8034,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,Tatooine,None

In [117]:
for x in df.index:
  if df.loc[x, 'Do_Not_Contact'] == 'Y':
    df.drop(x, inplace=True)
    
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-054-054-5054,"123 Shire Lane, Shire",Y,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-064-064-3097,93 West Main Street,N,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,-,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
4,1005,Jon,Snow,876-067-067-8034,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-076-076-2024,768 City Parkway,Y,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,-,1209 South Street,N,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-067-067-8034,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N0a---,123 Middle Earth,Y,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-054-054-5054,"25th Main Street, New York",Y,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,-,"612 Shire Lane, Shire",Y,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,-,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-054-054-3023,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-067-067-8034,343 City Parkway,Y,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-076-076-2024,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-054-054-5054,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-064-064-3097,"121 Paper Avenue, Pennsylvania",Y,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,-,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N0a---,,,Yes,True,,None,None
19,1020,Anakin,Skywalker,876-067-067-8034,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,Tatooine,None

In [118]:
df['Do_Not_Contact'] = df.replace('', 'N')

ValueError: Columns must be same length as key

In [120]:
for x in df.index:
    if df.loc[x, 'Phone_Number'] == 'Y':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-054-054-5054,"123 Shire Lane, Shire",Y,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-064-064-3097,93 West Main Street,N,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,-,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
4,1005,Jon,Snow,876-067-067-8034,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-076-076-2024,768 City Parkway,Y,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,-,1209 South Street,N,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-067-067-8034,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N0a---,123 Middle Earth,Y,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-054-054-5054,"25th Main Street, New York",Y,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,-,"612 Shire Lane, Shire",Y,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,-,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-054-054-3023,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-067-067-8034,343 City Parkway,Y,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-076-076-2024,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-054-054-5054,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-064-064-3097,"121 Paper Avenue, Pennsylvania",Y,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,-,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N0a---,,,Yes,True,,None,None
19,1020,Anakin,Skywalker,876-067-067-8034,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,Tatooine,None

In [125]:
df.reset_index(drop=True)
# df.drop('Index', axis=1)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip_Code
0,1001,Frodo,Baggins,123-054-054-5054,"123 Shire Lane, Shire",Y,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-064-064-3097,93 West Main Street,N,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,-,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1005,Jon,Snow,876-067-067-8034,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
4,1006,Ron,Swanson,304-076-076-2024,768 City Parkway,Y,Yes,True,768 City Parkway,None,None
5,1007,Jeff,Winger,-,1209 South Street,N,No,False,1209 South Street,None,None
6,1008,Sherlock,Holmes,876-067-067-8034,98 Clue Drive,N,No,False,98 Clue Drive,None,None
7,1009,Gandalf,NaN,N0a---,123 Middle Earth,Y,NaN,False,123 Middle Earth,None,None
8,1010,Peter,Parker,123-054-054-5054,"25th Main Street, New York",Y,No,True,25th Main Street,New York,None
9,1011,Samwise,Gamgee,-,"612 Shire Lane, Shire",Y,No,True,612 Shire Lane,Shire,None
10,1012,Harry,Potter,-,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
11,1013,Don,Draper,123-054-054-3023,2039 Main Street,Y,N,False,2039 Main Street,None,None
12,1014,Leslie,Knope,876-067-067-8034,343 City Parkway,Y,No,False,343 City Parkway,None,None
13,1015,Toby,Flenderson,304-076-076-2024,214 HR Avenue,N,No,False,214 HR Avenue,None,None
14,1016,Ron,Weasley,123-054-054-5054,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
15,1017,Michael,Scott,123-064-064-3097,"121 Paper Avenue, Pennsylvania",Y,No,False,121 Paper Avenue,Pennsylvania,None
16,1018,Clark,Kent,-,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
17,1019,Creed,Braton,N0a---,,,Yes,True,,None,None
18,1020,Anakin,Skywalker,876-067-067-8034,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,Tatooine,None